version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli@15

  pre_build:
    commands:
      - echo "Copying configuration files"
      - cp config/angular.json .
      - cp config/tsconfig.json .
      - cp config/tsconfig.app.json .

  build:
    commands:
      - npm install --legacy-peer-deps
      - ng build --configuration production

  post_build:
    commands:
      - mkdir -p deployment
      - cp -r dist/* deployment/
      - cp appspec.yml deployment/
      - cp -r scripts deployment/

artifacts:
  files:
    - '**/*'
  base-directory: 'deployment'
