version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies"
      - export NODE_OPTIONS="--max-old-space-size=4096"
      - npm config set fund false
      - npm config set audit false
      - npm install -g @angular/cli@16 --silent

  pre_build:
    commands:
      - echo "Pre-build phase"
      - ng version

  build:
    commands:
      - echo "Build phase started"
      - npm ci --silent --legacy-peer-deps
      - ng build --configuration production --verbose=false
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  base-directory: 'dist/angular-cicd-app'
