version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - npm install -g @angular/cli@15

  pre_build:
    commands:
      - echo "Creating configuration files"
      - ./create-config-files.sh

  build:
    commands:
      - npm install --legacy-peer-deps
      - npm install --save-dev @types/node@18.19.50
      - ng build --configuration production

  post_build:
    commands:
      - mkdir -p deployment
      - if [ -d "dist" ]; then cp -r dist/* deployment/; else echo "<h1>Build Failed</h1>" > deployment/index.html; fi
      - cp appspec.yml deployment/ || echo "Missing appspec.yml"
      - cp -r scripts deployment/ || echo "Missing scripts"
      - chmod +x deployment/scripts/*.sh || true

artifacts:
  files:
    - '**/*'
  base-directory: 'deployment'
